version: 2

jobs:
  build:
    working_directory: ~/circleci-docker
    environment:
      LIBRARY: feedyard
      CONTAINER_NAME: circleci-docker
      VERSION: 3.6
      BASH_ENV: .circlerc
    docker:
      - image: feedyard/circleci-docker #circleci/python:3.6.1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: confirm Docker
          command: 'docker info'
      - run:
          name: decrypt secrets
          command: 'openssl aes-256-cbc -d -in secrets.ci -out .circlerc -k $KEY'
      - run:
          name: build image
          command: 'docker build -t $LIBRARY/$CONTAINER_NAME:latest .'
      - run:
          name: tag with build version
          command: 'docker tag $LIBRARY/$CONTAINER_NAME:latest $LIBRARY/$CONTAINER_NAME:$VERSION.$CIRCLE_BUILD_NUM'
      - deploy:
          name: deploy to docker hub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push $LIBRARY/$CONTAINER_NAME:$VERSION.$CIRCLE_BUILD_NUM
            docker push $LIBRARY/$CONTAINER_NAME:latest